### ISSUE TITLE
[Question] Can I use your datapack as a base

### ISSUE THREAD

**Issue by V-lpen** [Blatko1/anytag#1]
Can I use your datapack as a base to make my own? I will credit yours for inspiration / borrowed commands! I have a cool idea that i think will be awesome

(Also sorry for making a github issue, i wasnt sure where else to contact you)

**Comment by Blatko1** [comment]
Yes! It's all right with me. You can do as you wrote. I am glad that it inspired you! Btw, I am sorry for the somewhat late reply.
